"""
Django settings for cerberus_django project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# from keycloak.keycloak_openid import KeycloakOpenID


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#
import os

# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#l(w)r$+2b+4xrmlo3$@bh=7r1u+^o#$y5u9e-p9b82$pb%%+x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_keycloak.apps.KeycloakAppConfig',
    'django_keycloak',
    'rest_framework',
    'accounts.apps.AccountsConfig',
    'base.apps.BaseConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_keycloak.middleware.KeycloakMiddleware',
    # 'accounts.middlewares.KeycloakMiddleware',
    # 'django_keycloak.middleware.BaseKeycloakMiddleware',
    # 'django-keycloak-auth.middleware.KeycloakMiddleware',
    # 'django_keycloak.middleware.BaseKeycloakMiddleware',
    # 'django_keycloak.middleware.RemoteUserAuthenticationMiddleware',
]

KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.OpenIdConnectProfile'
KEYCLOAK_REMOTE_USER_MODEL = 'django_keycloak.remote_user.KeycloakRemoteUser'

# KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
#     'admin', 'accounts',
#     ]
# CONFIG_DIR = os.path.join(os.path.dirname(__file__))
# print("Config dir...",CONFIG_DIR)
# KEYCLOAK_CLIENT_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
# MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmZXbaAH4VB56Op3piChTopZ+/AUzJQGVGcq9T/v0abEMOoEyTlHzlGrofOCrOG0PK4wm84Af//qrlOWc5uN6OrmYeJckXpTg3ctAuy0BBM9ffteg6IqZR9Zj6jEnsJ1D6A0VVyma64HORdR7YwGswlB91IxRq2wAttyzajgS6b9Lygan7GWI9FgFTamBRF88e91a3RwVRCsrh7cjBSaMft3hpi2qt4sQjEK1Otr0SV5OmtmRnNck6+mMWX/PHYle98u6A42c7ikcGy5tS9x6afJA7wZTIOCagkQAvBaE3nDvKu7OmaGGKkTObL08ECbvt545npISp84QmVFdIntO3wIDAQAB
# -----END PUBLIC KEY-----"""
# KEYCLOAK_CONFIG = {
#     'KEYCLOAK_REALM': 'cerberus',
#     'KEYCLOAK_CLIENT_ID': 'cerberus-client',
#     'KEYCLOAK_DEFAULT_ACCESS': 'ALLOW', # DENY or ALLOW
#     'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(CONFIG_DIR , 'authorization-config.json'),
#     'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'DECODE',
#     'KEYCLOAK_SERVER_URL': 'http://KEYCLOAK_HOST:8088/auth/',
#     'KEYCLOAK_CLIENT_SECRET_KEY': 'MIICrTCCAZUCBgGFklXgXjANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwHhcNMjMwMTA4MTcwMTE5WhcNMzMwMTA4MTcwMjU5WjAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCUAMomq/3SiyFKJK8DsCvHOcNu4nnz+DNV28HQXXUCMy9M3ZtPc5v+zHaamNgDrc2NuReuP6jGgAysFxFcUuIt9JbxuTS9fQB5g/dzMRfWcosbEGjIygLo4wOrm3rfyrq2EjRCU83RWGa1Lfhz+bbuJ5Xe03DE976g0TdAI5BYAbLkMw0mUPZr9YuFGFpHd+vK9KkMDKP/Rp4RrtuXAEoq7xCKrp59PLnVZiEovJ9ktpsI0Ti5gPz0KCjSGn2tjFtX2WmpI1BChUY8w0Ann67sImzVuf4HOjzCetCwotGEDAvWuecqR3lAD8WpgRQBdaZcUL/nq1jC3+mZ9UAmdpeLAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAGuF7nM+K1dJFT4nd0+W9FTomilWqF0EmVg0P489940r1A5CTgpat5qbgdhVqFoDyP5hZ2X/so75BjI5F0ldydlG7USTniZ8c7j6ETMjZ1FTt+QMKQaBtE4cs9FI3LAXWmgSyHML10UBsdwEMIM7nUW7oxprmeBHxeoaekxfQsFlGH0DTxi2xNStiQVDxPI0O+2/1T/jJ3ZauDvzITsoD11I6sFbFtksddXYh+bSo27Bf163k+Qsxo73ta86UknLgms3sxPFGHm/3b1IG9VackgOoWnGYjw18aeq7ej4ZHalyDAiYlpKAlH2aefZwklJmVKyr8GeYImglETpxorfuHo=',
#     'KEYCLOAK_CLIENT_PUBLIC_KEY': KEYCLOAK_CLIENT_PUBLIC_KEY, 
# }

# KEYCLOAK_EXEMPT_URIS = []
# KEYCLOAK_CONFIG = {
#     'KEYCLOAK_SERVER_URL': 'http://localhost:8080/auth',
#     'KEYCLOAK_REALM': 'cerberus',
#     'KEYCLOAK_CLIENT_ID': 'cerberus-client',
#     'KEYCLOAK_CLIENT_SECRET_KEY': 'MIICrTCCAZUCBgGFklXgXjANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwHhcNMjMwMTA4MTcwMTE5WhcNMzMwMTA4MTcwMjU5WjAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCUAMomq/3SiyFKJK8DsCvHOcNu4nnz+DNV28HQXXUCMy9M3ZtPc5v+zHaamNgDrc2NuReuP6jGgAysFxFcUuIt9JbxuTS9fQB5g/dzMRfWcosbEGjIygLo4wOrm3rfyrq2EjRCU83RWGa1Lfhz+bbuJ5Xe03DE976g0TdAI5BYAbLkMw0mUPZr9YuFGFpHd+vK9KkMDKP/Rp4RrtuXAEoq7xCKrp59PLnVZiEovJ9ktpsI0Ti5gPz0KCjSGn2tjFtX2WmpI1BChUY8w0Ann67sImzVuf4HOjzCetCwotGEDAvWuecqR3lAD8WpgRQBdaZcUL/nq1jC3+mZ9UAmdpeLAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAGuF7nM+K1dJFT4nd0+W9FTomilWqF0EmVg0P489940r1A5CTgpat5qbgdhVqFoDyP5hZ2X/so75BjI5F0ldydlG7USTniZ8c7j6ETMjZ1FTt+QMKQaBtE4cs9FI3LAXWmgSyHML10UBsdwEMIM7nUW7oxprmeBHxeoaekxfQsFlGH0DTxi2xNStiQVDxPI0O+2/1T/jJ3ZauDvzITsoD11I6sFbFtksddXYh+bSo27Bf163k+Qsxo73ta86UknLgms3sxPFGHm/3b1IG9VackgOoWnGYjw18aeq7ej4ZHalyDAiYlpKAlH2aefZwklJmVKyr8GeYImglETpxorfuHo=',
# }

# keycloak_openid = KeycloakOpenID(
#     server_url="https://localhost:8080/auth/",
#     client_id="cerberus-client",
#     realm_name="cerberus",
#     client_secret_key='MIICrTCCAZUCBgGFklXgXjANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwHhcNMjMwMTA4MTcwMTE5WhcNMzMwMTA4MTcwMjU5WjAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCUAMomq/3SiyFKJK8DsCvHOcNu4nnz+DNV28HQXXUCMy9M3ZtPc5v+zHaamNgDrc2NuReuP6jGgAysFxFcUuIt9JbxuTS9fQB5g/dzMRfWcosbEGjIygLo4wOrm3rfyrq2EjRCU83RWGa1Lfhz+bbuJ5Xe03DE976g0TdAI5BYAbLkMw0mUPZr9YuFGFpHd+vK9KkMDKP/Rp4RrtuXAEoq7xCKrp59PLnVZiEovJ9ktpsI0Ti5gPz0KCjSGn2tjFtX2WmpI1BChUY8w0Ann67sImzVuf4HOjzCetCwotGEDAvWuecqR3lAD8WpgRQBdaZcUL/nq1jC3+mZ9UAmdpeLAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAGuF7nM+K1dJFT4nd0+W9FTomilWqF0EmVg0P489940r1A5CTgpat5qbgdhVqFoDyP5hZ2X/so75BjI5F0ldydlG7USTniZ8c7j6ETMjZ1FTt+QMKQaBtE4cs9FI3LAXWmgSyHML10UBsdwEMIM7nUW7oxprmeBHxeoaekxfQsFlGH0DTxi2xNStiQVDxPI0O+2/1T/jJ3ZauDvzITsoD11I6sFbFtksddXYh+bSo27Bf163k+Qsxo73ta86UknLgms3sxPFGHm/3b1IG9VackgOoWnGYjw18aeq7ej4ZHalyDAiYlpKAlH2aefZwklJmVKyr8GeYImglETpxorfuHo=',
# )

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_keycloak.backends.KeycloakAuthenticationBackend',
)


KEYCLOAK_CONFIG = {
    # The Keycloak's Public Server URL (e.g. http://localhost:8080)
    'SERVER_URL': 'http://optimistic_goldstine:8080',
    # The Keycloak's Internal URL 
    # (e.g. http://keycloak:8080 for a docker service named keycloak)
    # Optional: Default is SERVER_URL
    'INTERNAL_URL': 'http://optimistic_goldstine:8080',
    # Override for default Keycloak's base path
    # Default is '/auth/'
    'BASE_PATH': '/auth/',
    # The name of the Keycloak's realm
    'REALM': 'cerberus',
    # The ID of this client in the above Keycloak realm
    'CLIENT_ID': 'cerberus-client',
    # The secret for this confidential client
    'CLIENT_SECRET_KEY': 'MIICrTCCAZUCBgGFmnJK3zANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwHhcNMjMwMTEwMDY0OTE5WhcNMzMwMTEwMDY1MDU5WjAaMRgwFgYDVQQDDA9jZXJiZXJ1cy1jbGllbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCjZfH/5Ux94SqkPoPOrKMLb8B/lQpXH0wFjiTD2ltBdo308Jxc9z/ckwlcR3mWTOT3TtftUOGvL0/pIVs9v8xLOCkm91pNxFIxEjhaiJb1s0DqK5rjq4ByM6emnvmq4YTp3IH4jfGADESGJ5O8rBYPg/Kb2TvlfvnoxJyj+PgFJf01owNrETrgLTUoRUE2pKWot7lSDQapOAaMMiUJ3yokaB6CDZytSnWwAKBDcSyyxvGOCdVdUShm9zfcAhXd1HwPOeMP85kgwR4P23gdk65p0X+0WqfvyVr84o50I3+4DFMsi825u5uDFmazkoEmfvNbcvXUDA9lXMqbtFtG0zktAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAHsonCn6zVof5fuhKpyllF5/PVDZcj7RCnJ/PgceEAcq0VTGtGAACHaSA1FYftVv//zuQVwtPhBsmU7fJFZs3vj8xwqgsSdliX6mVD3jwiEXpXslq5/z2w3ilN9/uBpZAvjLyBg/liFa0sK6Al41lPEY8raJe0rs3A/NteEjYbM+E1f2tjQUVMjWTPKkNgua1Io4EKWrmuLnR8WmN+3du5/6QDOlOqsg7RGtghPaukrozK/jO5kfldRTy7tsF+yI4aSLfqr6e5gzzzUKeLFcPquP4zteioBoFsT7Cnsl69eZy0CbHimPQ4k1QoW+OWTqc67f9HwmeBq2SXcr/5quXkk=',
    # The name of the admin role for the client
    'CLIENT_ADMIN_ROLE': 'super-user-policy',
    # The name of the admin role for the realm
    'REALM_ADMIN_ROLE': 'super-user-policy',
    # Regex formatted URLs to skip authentication
    'EXEMPT_URIS': [],
    # Flag if the token should be introspected or decoded (default is False)
    'DECODE_TOKEN': False,
    # Flag if the audience in the token should be verified (default is True)
    'VERIFY_AUDIENCE': True,
    # Flag if the user info has been included in the token (default is True)
    'USER_INFO_IN_TOKEN': True,
    # Flag to show the traceback of debug logs (default is False)
    'TRACE_DEBUG_LOGS': False,
    # The token prefix that is expected in Authorization header (default is 'Bearer')
    'TOKEN_PREFIX': 'Bearer'
}


ROOT_URLCONF = 'cerberus_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cerberus_django.wsgi.application'

# AUTH_USER_MODEL = "accounts.NewUser"
# AUTH_USER_MODEL = "django_keycloak.KeycloakUserAutoId"

REST_FRAMEWORK = {
    # ... other rest framework settings.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',
        'django_keycloak.authentication.KeycloakAuthentication'
    ],
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('DATABASE_SERVER_HOSTNAME'),
        'PORT': os.environ.get('DATABASE_SERVER_PORTNUMBER'),
        'NAME': os.environ.get('DATABASE_SERVER_DATABASENAME'),
        'USER': os.environ.get('DATABASE_SERVER_USERNAME'),
        'PASSWORD': os.environ.get('DATABASE_SERVER_PASSWORD'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# EMail Configuration

MAIL_SERVER_HOSTNAME = os.environ.get('MAIL_SERVER_HOSTNAME')
MAIL_SERVER_PORTNUMBER = os.environ.get('MAIL_SERVER_PORTNUMBER')
MAIL_SERVER_SECURITYFLAG = os.environ.get('MAIL_SERVER_SECURITYFLAG')
MAIL_SERVER_USERNAME = os.environ.get('MAIL_SERVER_USERNAME')
MAIL_SERVER_PASSWORD = os.environ.get('MAIL_SERVER_PASSWORD')

# 

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
